### ISSUE TITLE
Licence changed from LGPL to ALv2 ?

### ISSUE THREAD

**Issue by ptitjes** [jpace/java-diff#1]
Hi,

I've seen that you changed the licence of java-diff from LGPL to ALv2 ?

If you really need it to be ALv2, would you mind dual-licensing it with LGPL. There are a lot of free-software out there that use your library.

Thanks.
Ptitjes

**Comment by jpace** [comment]
Hi, and thanks for your request.

I've added the LGPL license file, COPYING.LESSER, so this can now be considered dual-licensed.

Thanks,
Jeff
